name       : z3
version    : 4.8.11
release    : 2
source     :
    - https://github.com/Z3Prover/z3/archive/z3-4.8.11.tar.gz : 99e912b9af76a17f8827f89afcf4da117736f3877a8bbdd737c548c6541009d7
license    : MIT
component  : programming.library
summary    : The Z3 Theorem Prover
description: |
    Z3 is a theorem prover from Microsoft Research.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
