name       : z3
version    : 4.8.14
release    : 6
source     :
    - https://github.com/Z3Prover/z3/archive/refs/tags/z3-4.8.14.tar.gz : 96a1f49a7701120cc38bfa63c02ff93be4d64c7926cea41977dedec7d87a1364
homepage   : https://z3prover.github.io/
license    : MIT
component  :
    - programming.library
    - ^python-z3 : programming.python
    - java : programming.java
summary    :
    - The Z3 Theorem Prover
    - ^python-z3 : Python bindings to z3
    - java : Java bindings to z3
description: |
    Z3 is a theorem prover from Microsoft Research.
builddeps  :
    - pkgconfig(gmp)
    - openjdk-11-devel
patterns   :
    - ^python-z3 :
        - /usr/lib*/python*
    - java :
        - /usr/share/java
        - /usr/lib*/*java*
environment: |
    export JAVA_HOME=/usr/lib64/openjdk-11
    export PATH=$JAVA_HOME/bin:$PATH
setup      : |
    %cmake_ninja -DZ3_USE_LIB_GMP=ON \
                 -DZ3_BUILD_JAVA_BINDINGS=ON \
                 -DZ3_BUILD_PYTHON_BINDINGS=ON \
                 -DPYTHON_EXECUTABLE=/usr/bin/python3 \
                 -DCMAKE_INSTALL_PYTHON_PKG_DIR=%libdir%/python%python3_version%/site-packages \
build      : |
    %ninja_build
install    : |
    %ninja_install
