name       : z3
version    : 4.12.1
release    : 9
source     :
    - https://github.com/Z3Prover/z3/archive/refs/tags/z3-4.12.1.tar.gz : a3735fabf00e1341adcc70394993c05fd3e2ae167a3e9bb46045e33084eb64a3
homepage   : https://z3prover.github.io/
license    : MIT
component  :
    - programming.library
    - ^python-z3 : programming.python
    - java : programming.java
summary    :
    - The Z3 Theorem Prover
    - ^python-z3 : Python bindings to z3
    - java : Java bindings to z3
description: |
    Z3 is a theorem prover from Microsoft Research.
builddeps  :
    - pkgconfig(gmp)
    - openjdk-17-devel
patterns   :
    - ^python-z3 :
        - /usr/lib*/python*
    - java :
        - /usr/share/java
        - /usr/lib*/*java*
environment: |
    export JAVA_HOME=/usr/lib64/openjdk-17
    export PATH=$JAVA_HOME/bin:$PATH
setup      : |
    %cmake_ninja -DZ3_USE_LIB_GMP=ON \
                 -DZ3_BUILD_JAVA_BINDINGS=ON \
                 -DZ3_BUILD_PYTHON_BINDINGS=ON \
                 -DPYTHON_EXECUTABLE=/usr/bin/python3 \
                 -DCMAKE_INSTALL_PYTHON_PKG_DIR=%libdir%/python%python3_version%/site-packages \
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_build test-z3
    ./solusBuildDir/test-z3 -a
