name       : z3
version    : 4.8.13
release    : 4
source     :
    - https://github.com/Z3Prover/z3/archive/refs/tags/z3-4.8.13.tar.gz : 59a0b35711fa7ae48dd535116d2067a6a16955fcbf2623c516a3f630cd2832d8
license    : MIT
component  : programming.library
summary    : The Z3 Theorem Prover
description: |
    Z3 is a theorem prover from Microsoft Research.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
